[tool.briefcase]
project_name = "Boga"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/boga"
license = "MIT license"
author = 'Jose Prado'
author_email = "jose@example.com"

[tool.briefcase.app.boga]
formal_name = "Boga"
description = "My first application"
icon = "src/boga/resources/boga"
sources = ['src/boga']
requires = []


[tool.briefcase.app.boga.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.boga.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.boga.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.boga.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.boga.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
